In [2]:
import numpy as np # 
import pandas as pd

import warnings 
warnings.filterwarnings("ignore")

In [11]:
s=pd.Series(list(range(10,51,10)))
print(s)
l=list(range(10,51,10))
print(l)
s_i=pd.Series(list(range(10,51,10)),index=["a","b","c","d","e"])
print(s_i)
print(s_i[0])
print(s_i["a"])

0    10
1    20
2    30
3    40
4    50
dtype: int64
[10, 20, 30, 40, 50]
a    10
b    20
c    30
d    40
e    50
dtype: int64
10
10

In [12]:
print(s)
df=pd.DataFrame(s)
print(df)

0    10
1    20
2    30
3    40
4    50
dtype: int64
    0
0  10
1  20
2  30
3  40
4  50

In [15]:
n=[["Harry",25,27],
   ["Joe",34,32],
   ["Tom",28,30]
  ]
df=pd.DataFrame(n,columns=["Name","Python","ML"])
df

    Name  Python  ML
0  Harry      25  27
1    Joe      34  32
2    Tom      28  30

In [17]:
d={"Name":["Harry","Joe","Tom"],
   "Python":[25,34,28],
   "ML":[27,32,30]}
df=pd.DataFrame(d)
df

    Name  Python  ML
0  Harry      25  27
1    Joe      34  32
2    Tom      28  30

In [28]:
df1=pd.DataFrame(
    {
        "emp_id":[1,2,3,4],
        "name":["Alice","Bob","Charlie","David"]
    }
)
df2=pd.DataFrame(
    {
        "id":[1,2,3,4],
        "name":["Alice","Bob","Charlie","David"]
    }
)
df3=pd.DataFrame(
    {
        "id":[2,3,6,7],
        "salary":[50000,60000,534767,32675]
    }
)
df4=pd.merge(df2,df3,how="outer",on="id")
print(df4)
df5=pd.merge(df1,df3,how="inner",left_on="emp_id",right_on="id")
print(df5)
print(type(s))

   id     name    salary
0   1    Alice       NaN
1   2      Bob   50000.0
2   3  Charlie   60000.0
3   4    David       NaN
4   6      NaN  534767.0
5   7      NaN   32675.0
   emp_id     name  id  salary
0       2      Bob   2   50000
1       3  Charlie   3   60000
<class 'pandas.core.series.Series'>

In [32]:
d={
    "city":["NY","NY","LA","LA"],
    "year":[21,22,21,22],
    "sales" :[100,150,200,250]
}
df=pd.DataFrame(d)
print(df)
p=pd.pivot_table(df,
                index="city",
                columns="year",
                values="sales",
                aggfunc="sum")
print(p)
ct=pd.crosstab(df["city"],df["year"])
print(ct)

  city  year  sales
0   NY    21    100
1   NY    22    150
2   LA    21    200
3   LA    22    250
year   21   22
city
LA    200  250
NY    100  150
year  21  22
city
LA     1   1
NY     1   1

In [34]:
df.to_csv("emp_data.csv",index=None)

In [35]:
a=pd.read_csv("emp_data.csv")
a

  city  year  sales
0   NY    21    100
1   NY    22    150
2   LA    21    200
3   LA    22    250