In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
s=pd.Series([1,2,3,4,5],index=[60,61,62,63,64])
print(s)
print(type(s))
print(s[60])
s=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(s)
print(s["a"])
print(s[0])

60    1
61    2
62    3
63    4
64    5
dtype: int64
<class 'pandas.core.series.Series'>
1
a    1
b    2
c    3
d    4
e    5
dtype: int64
1
1

In [3]:
# dataframe -- 2 ways-- dictionaries, list

In [4]:
# dictionaries
d={
    "student_id":[1,2,3,4,5,6,7,8,9],
    "Name":["April","Autumn","Rose","Lily","Mary","Tom","Jerry","Bob","Harry"],
    "Marks":[89,80,90,88,87,90,99,89,87]
}
df=pd.DataFrame(d)
print(df.head(1))
print(df.tail(4))
print(df.sample(4))

   student_id   Name  Marks
0           1  April     89
   student_id   Name  Marks
5           6    Tom     90
6           7  Jerry     99
7           8    Bob     89
8           9  Harry     87
   student_id    Name  Marks
1           2  Autumn     80
7           8     Bob     89
5           6     Tom     90
3           4    Lily     88

In [5]:
d={"id":[1,2,3,4,5],
   "Name":["April","Autumn","Rose","Lily","Mary"],
    "Marks":[89,80,90,88,87]
  }
df1=pd.DataFrame(d)
print(df1)

d={
    "student_id":[1,2,3],
    "age":[13,14,15]
}
df2=pd.DataFrame(d)
print(df2)
df3=pd.merge(df1,df2,left_on="id",right_on="student_id",how="inner")
df3

   id    Name  Marks
0   1   April     89
1   2  Autumn     80
2   3    Rose     90
3   4    Lily     88
4   5    Mary     87
   student_id  age
0           1   13
1           2   14
2           3   15

   id    Name  Marks  student_id  age
0   1   April     89           1   13
1   2  Autumn     80           2   14
2   3    Rose     90           3   15

In [6]:
df1=pd.DataFrame({"emp_id":[1,2,3,4],
                  "name":["Alice","Bob","Charlie","David"]})
df2=pd.DataFrame({"id":[1,2,3,4],
                  "name":["Alice","Bob","Charlie","David"]})
df3=pd.DataFrame({"id":[2,3,5],
                  "salary":[50000,60000,45000]})

'''
l=[[1,"Alice"],[2,"Bob"],[3,"Charlie"],[4,"David"]]
pd.DataFrame(l,columns=["emp_id","name"])
'''
df4=pd.merge(df2,df3,on="id",how="inner")
print(df4)
df5=pd.merge(df1,df3,left_on="emp_id",right_on="id",how="inner")
df5

   id     name  salary
0   2      Bob   50000
1   3  Charlie   60000

   emp_id     name  id  salary
0       2      Bob   2   50000
1       3  Charlie   3   60000

In [7]:
df=pd.read_csv("Studentsnew.csv")
df.head(2)

     Rank     Name  Age  Gender Background  Python  Machine Learning
0  Rank 1     Ravi   23    Male       Tech      89                95
1  Rank 2  Chandni   22  Female   Non-Tech      78                83

In [8]:
df.tail(2)

      Rank    Name  Age  Gender Background  Python  Machine Learning
8   Rank 9  Neelam   24  Female   Non-Tech      50                47
9  Rank 10  Mangal   22    Male   Non-Tech      45                46

In [9]:
df.sample(2)

     Rank       Name  Age  Gender Background  Python  Machine Learning
5  Rank 6  Pratiksha   24  Female   Non-Tech      58                55
2  Rank 3    Gyanesh   25    Male       Tech      70                80

In [10]:
df.info() #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              10 non-null     object
 1   Name              10 non-null     object
 2   Age               10 non-null     int64
 3   Gender            10 non-null     object
 4   Background        10 non-null     object
 5   Python            10 non-null     int64
 6   Machine Learning  10 non-null     int64
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes

In [11]:
df.describe() # gives a quick statistical distribution understanding of data.
'''
        Age	        Python	    Machine Learning
mean	22.800000	62.300000	65.100000
50%	    22.500000	59.000000	62.500000
mean>median - python - +ve skewnes
mean=median - age - normally distrbuted
mean>medain - ML - +ve skewness
'''

'\n        Age\t        Python\t    Machine Learning\nmean\t22.800000\t62.300000\t65.100000\n50%\t    22.500000\t59.000000\t62.500000\nmean>median - python - +ve skewnes\nmean=median - age - normally distrbuted\nmean>medain - ML - +ve skewness\n'

In [12]:
df["Python"]

0    89
1    78
2    70
3    68
4    60
5    58
6    55
7    50
8    50
9    45
Name: Python, dtype: int64

In [13]:
df.Python

0    89
1    78
2    70
3    68
4    60
5    58
6    55
7    50
8    50
9    45
Name: Python, dtype: int64

In [14]:
df["Machine Learning"]

0    95
1    83
2    80
3    75
4    70
5    55
6    50
7    50
8    47
9    46
Name: Machine Learning, dtype: int64

In [15]:
# Feature engineering
df["Total"]=df["Machine Learning"]+df["Python"]

In [16]:
df.head()

     Rank     Name  Age  Gender Background  Python  Machine Learning  Total
0  Rank 1     Ravi   23    Male       Tech      89                95    184
1  Rank 2  Chandni   22  Female   Non-Tech      78                83    161
2  Rank 3  Gyanesh   25    Male       Tech      70                80    150
3  Rank 4    Rahul   22    Male       Tech      68                75    143
4  Rank 5   Kartik   23    Male       Tech      60                70    130

In [17]:
cc=df.select_dtypes(object)
cc

      Rank       Name  Gender Background
0   Rank 1       Ravi    Male       Tech
1   Rank 2    Chandni  Female   Non-Tech
2   Rank 3    Gyanesh    Male       Tech
3   Rank 4      Rahul    Male       Tech
4   Rank 5     Kartik    Male       Tech
5   Rank 6  Pratiksha  Female   Non-Tech
6   Rank 7       Maya  Female   Non-Tech
7   Rank 8      Shani    Male       Tech
8   Rank 9     Neelam  Female   Non-Tech
9  Rank 10     Mangal    Male   Non-Tech

In [18]:
for i in cc:
    print(f"{df[i].value_counts()}")

Rank
Rank 1     1
Rank 2     1
Rank 3     1
Rank 4     1
Rank 5     1
Rank 6     1
Rank 7     1
Rank 8     1
Rank 9     1
Rank 10    1
Name: count, dtype: int64
Name
Ravi         1
Chandni      1
Gyanesh      1
Rahul        1
Kartik       1
Pratiksha    1
Maya         1
Shani        1
Neelam       1
Mangal       1
Name: count, dtype: int64
Gender
Male      6
Female    4
Name: count, dtype: int64
Background
Tech        5
Non-Tech    5
Name: count, dtype: int64

In [19]:
df["Background"].unique()# nunique()

array(['Tech', 'Non-Tech'], dtype=object)

In [20]:
df["Gender"]=df["Gender"].replace({"Male":0,"Female":1})

In [21]:
df.head(2)

     Rank     Name  Age  Gender Background  Python  Machine Learning  Total
0  Rank 1     Ravi   23       0       Tech      89                95    184
1  Rank 2  Chandni   22       1   Non-Tech      78                83    161

In [22]:
df["Background"]=df["Background"].replace({'Tech':0,'Non-Tech':1})

In [23]:
df.head(2)

     Rank     Name  Age  Gender  Background  Python  Machine Learning  Total
0  Rank 1     Ravi   23       0           0      89                95    184
1  Rank 2  Chandni   22       1           1      78                83    161

In [25]:
df[["Age","Machine Learning","Total"]]

   Age  Machine Learning  Total
0   23                95    184
1   22                83    161
2   25                80    150
3   22                75    143
4   23                70    130
5   24                55    113
6   22                50    105
7   21                50    100
8   24                47     97
9   22                46     91